apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.manifest.back }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.manifest.back }}
  template:
    metadata:
      labels:
        app: {{ .Values.manifest.back }}
    spec:
      containers:
      - name: {{ .Values.manifest.back }}
        image: imsalyunus/cilist-bee-imsal:latest
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef: 
              name: cmap
        resources:
